!include make.inc

TARGETS = $(NG).ng
DEPENDENTS = debugext\debugext.ngo filesys\filesys.ngo &
                mathlib\mathlib.ngo lang\lang.ngo

$(NG).ng: $(NG).lnk $(DEPENDENTS)

$(BUILD)


