#ifndef RR2NW_RECOVERED_ARENA_SEANCE_RUNTIME_H
#define RR2NW_RECOVERED_ARENA_SEANCE_RUNTIME_H

class SimulationContext;

enum ERecoveredArenaSeanceIssue {
  RECOVERED_ARENA_SEANCE_INVALID_CONTEXT = 1u << 0,
  RECOVERED_ARENA_SEANCE_OPEN_FAILURE = 1u << 1,
  RECOVERED_ARENA_SEANCE_SCRIPT_ALLOCATION_FAILURE = 1u << 2,
  RECOVERED_ARENA_SEANCE_SCRIPT_INITIALIZATION_FAILURE = 1u << 3,
  RECOVERED_ARENA_SEANCE_SCRIPT_COMPILE_FAILURE = 1u << 4,
  RECOVERED_ARENA_SEANCE_SCRIPT_PROCESS_FAILURE = 1u << 5,
  RECOVERED_ARENA_SEANCE_SCRIPT_TIMEOUT = 1u << 6,
  RECOVERED_ARENA_SEANCE_VEHICLE_TABLE_MISSING = 1u << 7,
  RECOVERED_ARENA_SEANCE_VEHICLE_OBJECT_MISSING = 1u << 8,
  RECOVERED_ARENA_SEANCE_VEHICLE_INTERFACE_MISSING = 1u << 9,
  RECOVERED_ARENA_SEANCE_SCRIPT_HOST_FAILURE = 1u << 10,
  RECOVERED_ARENA_SEANCE_ROUTE_TABLE_MISSING = 1u << 11,
  RECOVERED_ARENA_SEANCE_SPARK_TABLE_MISSING = 1u << 12,
  RECOVERED_ARENA_SEANCE_SPARK_OBJECT_MISSING = 1u << 13,
  RECOVERED_ARENA_SEANCE_SPARK_DEFAULT_INVALID = 1u << 14,
  RECOVERED_ARENA_SEANCE_BIRD_TABLE_MISSING = 1u << 15,
  RECOVERED_ARENA_SEANCE_BIRD_OBJECT_MISSING = 1u << 16,
  RECOVERED_ARENA_SEANCE_BIRD_DEFAULT_INVALID = 1u << 17,
  RECOVERED_ARENA_SEANCE_PORTAL_TABLE_MISSING = 1u << 18,
  RECOVERED_ARENA_SEANCE_ORPHAN_TABLE_MISSING = 1u << 19,
  RECOVERED_ARENA_SEANCE_ORPHAN_OBJECT_MISSING = 1u << 20,
  RECOVERED_ARENA_SEANCE_ORPHAN_DEFAULT_INVALID = 1u << 21,
  RECOVERED_ARENA_SEANCE_ARTEFACT_TABLE_MISSING = 1u << 22,
  RECOVERED_ARENA_SEANCE_ARTEFACT_OBJECT_MISSING = 1u << 23,
  RECOVERED_ARENA_SEANCE_ARTEFACT_DEFAULT_INVALID = 1u << 24,
  RECOVERED_ARENA_SEANCE_SMOKE_ATTRIBUTE_TABLE_MISSING = 1u << 25,
  RECOVERED_ARENA_SEANCE_SMOKE_ATTRIBUTE_OBJECT_MISSING = 1u << 26,
  RECOVERED_ARENA_SEANCE_SMOKE_ATTRIBUTE_ROSTER_INVALID = 1u << 27,
  RECOVERED_ARENA_SEANCE_SMOKE_ATTRIBUTE_SOURCE_UNAVAILABLE = 1u << 28
};

int RecoveredArenaSeance_Initialize(SimulationContext* context,
                                    double startTime);
void RecoveredArenaSeance_Release();
bool RecoveredArenaSeance_IsOpen();
bool RecoveredArenaSeance_ScriptCompleted();
bool RecoveredArenaSeance_BirdAttributesReady();
bool RecoveredArenaSeance_PortalReady();
bool RecoveredArenaSeance_OrphanAttributesReady();
bool RecoveredArenaSeance_ArtefactAttributesReady();
bool RecoveredArenaSeance_SmokeAttributesReady();
bool RecoveredArenaSeance_SparkAttributesReady();
bool RecoveredArenaSeance_RouteReady();
bool RecoveredArenaSeance_VehicleReady();
unsigned int RecoveredArenaSeance_Issues();
const char* RecoveredArenaSeance_LastError();

#endif
