!include ..\make.inc

TARGETS=

!ifeq OPENGL 0
TARGETS += $(O)\MSKLN32A.OBJ $(O)\SBLOOP.OBJ
!endif

!ifneq DEBUG 0
TARGETS+= $(O)\LANDD.OBJ
!else
TARGETS+= $(O)\CLIP.OBJ $(O)\LAND.OBJ $(O)\CONTOUR.OBJ &
	$(O)\MAPTOOLS.OBJ $(O)\SHIP.OBJ $(O)\TRIANG.OBJ $(O)\POLY.OBJ &
	$(O)\SCRLINEA.OBJ $(O)\TEXT.OBJ $(O)\CLIP2D.OBJ $(O)\MOVIES.OBJ
!endif

$(BUILD)

