 {"s_Menu_EXIT",             s_Menu_EXIT,    0}, 
 {"s_Menu_SURRENDER",	     s_Menu_SURRENDER,0},
 {"s_Menu_MISSIONOK",	     s_Menu_MISSIONOK,0},

 {"s_MenuSetLocale",         s_MenuSetLocale, 0},
 {"s_CalibrateJoystick",     s_CalibrateJoystick, 0},
 {"s_ChangeJoystickParams",  s_ChangeJoystickParams, 0},
 {"s_ChangeMouseParams",     s_ChangeMouseParams, 0},
  
 {"s_Menu_Point0",           s_Menu_Point0, 0},
 {"s_Menu_Point1",           s_Menu_Point1, 0},
 {"s_Menu_Point2",           s_Menu_Point2, 0},
 {"s_Menu_Point3",           s_Menu_Point3, 0},
 {"s_Menu_Point4",           s_Menu_Point4, 0},
 {"s_Menu_Point5",           s_Menu_Point5, 0},
 {"s_Menu_Point6",           s_Menu_Point6, 0},
 {"s_Menu_Point7",           s_Menu_Point7, 0},
 {"s_Menu_Point8",           s_Menu_Point8, 0},
 
 {"s_lev_LOAD_SLOT0",        s_lev_LOAD_SLOT0, 0},
 {"s_lev_LOAD_SLOT1",        s_lev_LOAD_SLOT1, 0},
 {"s_lev_LOAD_SLOT2",        s_lev_LOAD_SLOT2, 0},
 {"s_lev_LOAD_SLOT3",        s_lev_LOAD_SLOT3, 0},
 {"s_lev_LOAD_SLOT4",        s_lev_LOAD_SLOT4, 0},
 {"s_lev_LOAD_SLOT5",        s_lev_LOAD_SLOT5, 0},
 {"s_lev_LOAD_SLOT6",        s_lev_LOAD_SLOT6, 0},
 {"s_lev_LOAD_SLOT7",        s_lev_LOAD_SLOT7, 0},

 {"s_lev_SAVE_SLOT0",        s_lev_SAVE_SLOT0, 0},
 {"s_lev_SAVE_SLOT1",        s_lev_SAVE_SLOT1, 0},
 {"s_lev_SAVE_SLOT2",        s_lev_SAVE_SLOT2, 0},
 {"s_lev_SAVE_SLOT3",        s_lev_SAVE_SLOT3, 0},
 {"s_lev_SAVE_SLOT4",        s_lev_SAVE_SLOT4, 0},
 {"s_lev_SAVE_SLOT5",        s_lev_SAVE_SLOT5, 0},
 {"s_lev_SAVE_SLOT6",        s_lev_SAVE_SLOT6, 0},
 {"s_lev_SAVE_SLOT7",        s_lev_SAVE_SLOT7, 0},

