  {"s_OpenEventData"  , s_OpenEventData  , 0},
  {"s_CloseEventData" , s_CloseEventData,  0},
  {"s_WriteInt"       , s_WriteInt,        0},
  {"s_WriteFloat"     , s_WriteFloat,      0},
  {"s_WriteVector"    , s_WriteVector,     0},
  {"s_WriteStr"       , s_WriteStr,        0},
  {"s_WriteObjectID"  , s_WriteObjectID,   0},
  {"s_IssueEvent"     , s_IssueEvent,      0},
  {"s_SendEventNow"   , s_SendEventNow,    0},
  {"s_SearchObjectID" , s_SearchObjectID,  0},
  {"s_AddClassTable"  , s_AddClassTable,   0},
  {"s_NewObject"      , s_NewObject,       0},
  {"s_NewObjectN"     , s_NewObjectN,      0},
  {"s_Descend"        , s_Descend,         0},
  {"s_Ascend"         , s_Ascend,          0},
  {"s_LoadRoute"      , s_LoadRoute,       0},

  {"s_CreateProjectTable", s_CreateProjectTable, 0},
  {"s_NewPNode",           s_NewPNode,           0},
  {"s_OpenProjectData",    s_OpenProjectData,    0},
  {"s_CloseProjectData",   s_CloseProjectData,   0},
  {"s_ProjectWriteInt",    s_ProjectWriteInt,    0},
  {"s_ProjectWriteFloat",  s_ProjectWriteFloat,  0},
  {"s_ProjectWriteStr",    s_ProjectWriteStr,    0},
  {"s_ProjectNodeSetLink", s_ProjectNodeSetLink, 0},
  {"s_PNodeNULL",          s_NodeNULL,           0},

  {"s_UpdateAttributes",   s_UpdateAttributes,   0},
  {"s_New",                s_New,                0},
  {"s_AttachObject",       s_AttachObject,       0},
  {"s_SetViewPoint",       s_SetViewPoint,       0},
  {"s_GetTime",            s_GetTime,            0},
  {"s_SetDamage",          s_SetDamage,          0},
  {"s_SetCommander",        s_SetCommander,        0},
  {"s_SearchSeanceClassTable", s_SearchSeanceClassTable, 0},
