#ifndef __HARDWARE_MSG__
#define __HARDWARE_MSG__

#ifndef __A_MSG_H__
#include "message/a_msg.h"
#endif


enum {
	CTRL_SET_CONTROL = HARDWARE_MESSAGE,
	CTRL_LINK_CONTROLS,
	CTRL_CLEAR,
	CTRL_LOAD_DEFAULT,
	CTRL_HARDWARE_EVENT,
    CTRL_CALIBRATE_JOYSTICK, 
    CTRL_CHANGE_MOUSE_PARAMS,
    CTRL_CHANGE_JOYSTICK_PARAMS,
	CTRL_REMOTE_EVENT,
	CTRL_REMOTE_EVENT_DATA,
	CTRL_REMOTE_EVENT_DATA_PREPARE,
	CTRL_REMOTE_HARDWARE_EVENT,
	CTRL_SUBSCRIBE, 
	CTRL_UNSUBSCRIBE,
	CTRL_DEL_SUBSCRIBE,
	CTRL_SET_HARDWARE,
	CTRL_ENABLE_HARDWARE,
	CTRL_SET_EXCLUSIVE,
	CTRL_SET_NORMAL,
	CTRL_RES_CHANGE,
	CTRL_SET_MOUSE_SENS,
	CTRL_SET_JOYSTICK_SENS,
	CTRL_SET_MOUSE_INV_STATE,
	CTRL_SET_JOYSTICK_INV_STATE,
	CTRL_RECORD_DEMO,
	CTRL_STOP_RECORD,
	CTRL_PLAY_DEMO,
	CTRL_STOP_DEMO,
	CTRL_NETWORK_EVENT,
};

enum{
	CTRL_BUTTONS_MSG = CTRL_MESSAGE,
    CTRL_CHAR,
	CTRL_MOUSE_MOVE_MSG,
	CTRL_JOYSTICK_MOVE_MSG,
};

#define CTRL_ACTION_RELEASE 1000
#define CTRL_EXTENDED_KEY  256


#endif // __HARDWARE_MSG__
