#ifndef __VEHICLE_MSG__
#define __VEHICLE_MSG__

#include "a_msg.h"

enum{
    VEHICLE_UPDATE_POS = VEHICLE_MESSAGE,
    EV_VEHICLE_POINT0,
    EV_VEHICLE_POINT1,
    EV_VEHICLE_POINT2,
    EV_VEHICLE_POINT3,
    EV_VEHICLE_POINT4,
    EV_VEHICLE_POINT5,
    EV_VEHICLE_POINT6,
    EV_VEHICLE_POINT7,
    EV_VEHICLE_POINT8,
    EV_VEHICLE_SETTAXI,
    EV_VEHICLE_ROTATETAXI,
    EV_VEHICLE_DROP_TAXI,
    EV_VEHICLE_FIRE,
    EV_VEHICLE_SKIPTIME,
    EV_VEHICLE_SURRENDER,
    EV_VEHICLE_MISSIONOK
};

#endif
