;========================================
ESP_u0		equ dword ptr [esp + 72]
ESP_v0		equ dword ptr [esp + 68]
ESP_du		equ dword ptr [esp + 64]
ESP_dv		equ dword ptr [esp + 60]
ESP_D_D		equ dword ptr [esp + 56]
ESP_D_F		equ dword ptr [esp + 52]
ESP_D_B		equ dword ptr [esp + 48]
ESP_num		equ dword ptr [esp + 44]
ESP_scr		equ dword ptr [esp + 40]
ESP_startVert	equ dword ptr [esp + 36]
ESP_endVert	equ dword ptr [esp + 32]
ESP_topVert	equ dword ptr [esp + 28]
ESP_bottomVert	equ dword ptr [esp + 24]
ESP_vertC	equ dword ptr [esp + 20]
ESP_count	equ dword ptr [esp + 16]
;========================================
