!include ..\..\make.inc

CPP += -i..

OTAR  = $(O)\attr.obj $(O)\classtab.obj $(O)\subject.obj $(O)\savefile.obj



strgw.lib: $(OTAR)
	wlib strgw.lib $(OTAR)


TARGETS = strgw.lib

$(BUILD)




