!include ..\..\make.inc

!ifneq DEBUG 0
T = OBJ\WD
!else
T = OBJ\WR
!endif


OTAR  = $(T)\bullet.obj $(T)\cannon.obj $(T)\Comander.obj 
OTAR += $(T)\DCross.obj 
OTAR += $(T)\Group.obj $(T)\Group_2.obj
OTAR += $(T)\Publish.obj $(T)\Spark.obj
OTAR += $(T)\Tank.obj $(T)\Tank_2.obj $(T)\Tank_3.obj $(T)\nearai.obj
OTAR += $(T)\t_dynobj.obj
OTAR += $(T)\Skin.obj $(T)\DynObj.obj $(T)\DynSpr.obj $(T)\dynpart.obj $(T)\dynpartln.obj
OTAR += $(T)\SkinSpr.obj
OTAR += $(T)\SoundObj.obj $(T)\WAVObj.obj
OTAR += $(T)\Fountain.obj $(T)\Smoke.obj $(T)\Smoker.obj
OTAR += $(T)\Vehicle.obj  $(T)\vh_dyn.obj $(T)\vh_vessel.obj $(T)\vs_zav.obj
OTAR += $(T)\explosion.obj
OTAR += $(T)\Bird.obj $(T)\Taxi.obj   $(T)\people.obj $(T)\pdy_obj.obj
OTAR += $(T)\Route.obj $(T)\route_i.obj
OTAR += $(T)\Farter.obj
OTAR += $(T)\StaticInit.obj $(T)\Staticobj.obj
OTAR += $(T)\menu.obj
OTAR += $(T)\dyncorona.obj
OTAR += $(T)\lamp.obj
OTAR += $(T)\dmap.obj
OTAR += $(T)\player.obj
OTAR += $(T)\corpse.obj
OTAR += $(T)\orphan.obj
OTAR += $(T)\Recrcen.obj
OTAR += $(T)\Artefact.obj $(T)\AnimPeop.obj $(T)\Portal.obj
OTAR += $(T)\Howitzer.obj

obasew.lib: $(OTAR)
	wlib obasew.lib $(OTAR)


TARGETS = obasew.lib

$(BUILD)




