!include ..\make.inc

TARGETS = $(O)\KEYBOARD.OBJ

!ifeq	NT 0
TARGETS += $(O)\HANDLER.OBJ
!endif

!ifneq	DEBUG 0
TARGETS += $(O)\INPUT.OBJ
!else
TARGETS += $(O)\MOUSE.OBJ $(O)\KEYDEFS.OBJ
!endif

$(BUILD)
