
func void LoadAllWaves(int classTableID)
{
    LoadWAV( classTableID, "wav.Steam2" , "steam2.wav",
                   15,//float  minFront,
                   15,//float  minBack,
                   100,//float  maxFront,
                   100,//float  maxBack,
                   1.0 //float  intensity
               );

    LoadWAV( classTableID, "wav.Steam1" , "steam1.wav",
                   15,//float  minFront,
                   15,//float  minBack,
                   100,//float  maxFront,
                   100,//float  maxBack,
                   1.0 //float  intensity
               );

    LoadWAV( classTableID, "wav.Factory" , "factory.wav",
                   50,//float  minFront,
                   50,//float  minBack,
                   200,//float  maxFront,
                   200,//float  maxBack,
                   1.0 //float  intensity
               );

    LoadWAV( classTableID, "wav.Factory2" , "factory2.wav",
                   50,//float  minFront,
                   50,//float  minBack,
                   200,//float  maxFront,
                   200,//float  maxBack,
                   1.0 //float  intensity
               );

    LoadWAV( classTableID, "wav.Windmill" , "wind3.wav",
                   50,//float  minFront,
                   50,//float  minBack,
                   150,//float  maxFront,
                   150,//float  maxBack,
                   0.7 //float  intensity
               );


    LoadWAV( classTableID, "wav.PassBy1" , "passby1.wav",
                   15,//float  minFront,
                   15,//float  minBack,
                   100,//float  maxFront,
                   100,//float  maxBack,
                   1.0 //float  intensity
               );

    LoadWAV( classTableID, "wav.FootStep1" , "fstep1.wav",
                   15,//float  minFront,
                   15,//float  minBack,
                   100,//float  maxFront,
                   100,//float  maxBack,
                   1.0 //float  intensity
               );

    LoadWAV( classTableID, "wav.FootStep2" , "fstep2.wav",
                   15,//float  minFront,
                   15,//float  minBack,
                   100,//float  maxFront,
                   100,//float  maxBack,
                   1.0 //float  intensity
               );


    LoadWAV( classTableID, "wav.Kalflash" , "Kalflash.wav",
                   15,//float  minFront,
                   15,//float  minBack,
                   100,//float  maxFront,
                   100,//float  maxBack,
                   1.0 //float  intensity
               );


    LoadWAV( classTableID, "wav.Ambient" , "Ambient.wav",
                   15,//float  minFront,
                   15,//float  minBack,
                   100,//float  maxFront,
                   100,//float  maxBack,
                   1.0 //float  intensity
               );


    LoadWAV( classTableID, "wav.Tank2" , "tank2.wav",
                   15,//float  minFront,
                   15,//float  minBack,
                   100,//float  maxFront,
                   100,//float  maxBack,
                   1.0  //float  intensity
               );


    LoadWAV( classTableID, "wav.Shoot.Gun1" , "gun1.wav",
                   50,//float  minFront,
                   50,//float  minBack,
                   250,//float  maxFront,
                   250,//float  maxBack,
                   1.0  //float  intensity
               );

    LoadWAV( classTableID, "wav.Shoot.Gun2" , "gun2.wav",
                   50,//float  minFront,
                   50,//float  minBack,
                   250,//float  maxFront,
                   250,//float  maxBack,
                   1.0  //float  intensity
               );

    LoadWAV( classTableID, "wav.Explosion", "Explosion1.wav",
                   100,//float  minFront,
                   100,//float  minBack,
                   1550,//float  maxFront,
                   1550,//float  maxBack,
                   1.0  //float  intensity
               );

    LoadWAV( classTableID, "wav.Helicopt", "Helicopt.wav",
                   15,//float  minFront,
                   15,//float  minBack,
                   100,//float  maxFront,
                   100,//float  maxBack,
                   1.0 //float  intensity
               );

    LoadWAV( classTableID, "wav.Engine2", "engine2.wav",
                   50,//float  minFront,
                   50,//float  minBack,
                   200,//float  maxFront,
                   200,//float  maxBack,
                   1.0  //float  intensity
               );

    LoadWAV( classTableID, "wav.Engine1", "engine1.wav",
                   15,//float  minFront,
                   15,//float  minBack,
                   100,//float  maxFront,
                   100,//float  maxBack,
                   1.0  //float  intensity
               );

    LoadWAV( classTableID, "wav.Engine7", "engine7.wav",
                   15,//float  minFront,
                   15,//float  minBack,
                   100,//float  maxFront,
                   100,//float  maxBack,
                   1.0  //float  intensity
               );

    LoadWAV( classTableID, "DummyBriefing","priest1.wav",
                   15,//float  minFront,
                   15,//float  minBack,
                   100,//float  maxFront,
                   100,//float  maxBack,
                   1.0  //float  intensity
               );

    LoadWAV( classTableID, "ConqBriefing","conqbrief.wav",
                   15,//float  minFront,
                   15,//float  minBack,
                   100,//float  maxFront,
                   100,//float  maxBack,
                   1.0  //float  intensity
               );

    LoadWAV( classTableID, "Spell","spell1.wav",
                   15,//float  minFront,
                   15,//float  minBack,
                   100,//float  maxFront,
                   100,//float  maxBack,
                   1.0  //float  intensity
               );

    LoadWAV( classTableID, "Doorsqueak","Doorsqueak.wav",
                   15,//float  minFront,
                   15,//float  minBack,
                   100,//float  maxFront,
                   100,//float  maxBack,
                   1.0  //float  intensity
               );

    LoadWAV( classTableID, "Drums","Drums.wav",
                   15,//float  minFront,
                   15,//float  minBack,
                   100,//float  maxFront,
                   100,//float  maxBack,
                   1.0  //float  intensity
               );

    LoadWAV( classTableID, "Ethnic","Ethnic.wav",
                   15,//float  minFront,
                   15,//float  minBack,
                   100,//float  maxFront,
                   100,//float  maxBack,
                   1.0  //float  intensity
               );


}
